site_name: docs.jwk.nz
site_description: Documentation for repositories that I have made
site_author: Jeffrey Kranenburg
site_url: https://docs.jwk.nz/

repo_name: jwknz/docs.jwk.nz
repo_url: https://github.com/jwknz/docs.jwk.nz
edit_uri: 'edit/master/docs/'

theme:
    docs_dir: docs
    name: material
    font:
        text: Roboto
        code: Roboto Mono
    palette:
        primary: 'blue'
        accent: 'red'
    # feature:
    #     tabs: 'true'


markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.sane_lists
  - markdown.extensions.meta
  - markdown.extensions.tables
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2019 and maintained by <a href="https://twitter.com/jwknz">Jeff Kranenburg</a>

plugins:
    - search

extra:
    social:
    - type: 'github'
      link: 'https://github.com/jwknz'
    - type: 'github'
      link: 'https://github.com/to-jk11'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jwknz'
    - type: 'twitter'
      link: 'https://twitter.com/jwknz'

extra_css:
  - 'stylesheets/extra.css'

# extra_javascript:
#     - assets/scripts/external_links.js